import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#091d24",
  },
  viewTitle: {
    width: "100%",
    height: "15%",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  viewInformation: {
    width: "100%",
    height: "auto",
    backgroundColor: "#fea200",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 1,
    paddingTop: 10,
  },
  text: {
    textAlign: "justify",
    fontSize: 16,
    color: "#000",
    width: "97%",
  },
  btnNews: {
    width: "75%",
    height: 40,
    backgroundColor: "#005CFE",
    borderRadius: 5,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 250,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-start",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContainer: {
    width: "98%",
    height: "95%",
    padding: 20,
    backgroundColor: "#fea200",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "flex-start",
    alignSelf: "center",
    paddingBottom: 20,
  },
  modalContent: {
    backgroundColor: "#fea200",
    width: "100%",
    height: "auto",
    maxHeight: "auto",
    borderRadius: 10,
    padding: 10,
  },
  modalItem: {
    marginBottom: 15,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#000000",
    width: "100%",
  },
  modalItemImage: {
    width: "200%",
    height: 400,
    marginBottom: 10,
    alignSelf: "center",
  },
  btnCommon: {
    width: "auto",
    height: 40,
    borderRadius: 5,
    backgroundColor: "#005CFE",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    marginTop: 15,
    alignSelf: "center",
  },
  commonBtnText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    textAlign: "center",
  },
  textAbout: {
    width: "95%",
    height: "auto",
    textAlign: "justify",
  },
  btnsBox: {
    width: "100%",
    marginTop: 10,
    alignItems: "center",
    paddingBottom: 20,
  },
  imageContainer: {
    width: "100%",
    height: 200,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: -35,
  },
  imageOutsideText: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
  },
  mainInformationContainer: {
    marginBottom: 15,
    alignItems: "flex-start",
    width: "100%",
  },
  modalText: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 10,
    color: "#333",
    textAlign: "left",
  },
  input: {
    width: "100%",
    height: 55,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    marginBottom: 20,
    paddingHorizontal: 10,
    fontSize: 16,
    backgroundColor: "#fff",
  },
  scrollViewContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  separator: {
    height: 2,
    backgroundColor: "black",
    width: "100%",
    marginVertical: 10,
  },
  modalDescription: {
    fontSize: 16,
    textAlign: "justify",
    marginBottom: -8,
    fontWeight: "bold",
  },
});

/* === Estilos para el card "Curso habilitado" === */
export const cursoCardStyles = StyleSheet.create({
  card: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#000000ff",
    backgroundColor: "rgba(0,92,254,0.08)",
    marginBottom: 8,
  },
  cardDisabled: {
    borderColor: "#cfcfcf",
    backgroundColor: "#f6f7f9",
    borderStyle: "dashed",
  },
  
  iconWrapDisabled: { backgroundColor: "#d3d7de" },
  iconText: { fontSize: 22, color: "#fff" },
  title: { fontSize: 16, fontWeight: "700", color: "#13213A" },
  titleDisabled: { color: "#8a8f98", fontWeight: "600" },
  chipsRow: { flexDirection: "row", gap: 8, marginTop: 6, flexWrap: "wrap" },
  chip: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 12,
    overflow: "hidden",
  },
  chipOk: { backgroundColor: "#DCF3D6", color: "#1A7F37" },
  chipWarn: { backgroundColor: "#FFE7E7", color: "#9B1C1C" },
  chipMode: { backgroundColor: "#E6F0FF", color: "#0B4EC2" },
});

export default styles;
