import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    width: "95%",
    alignItems: "center",
    marginTop: 4,
    marginBottom: 8,
  },
  boton: {
    width: "92%",
    minHeight: 42,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#005CFE",
  },
  textoBoton: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
    textAlign: "center",
  },
  deshabilitado: { opacity: 0.65 },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 10,
  },
  modal: {
    width: "98%",
    maxHeight: "92%",
    backgroundColor: "#FEA200",
    borderRadius: 16,
    padding: 12,
    alignItems: "center",
  },
  titulo: {
    color: "#111827",
    fontSize: 19,
    fontWeight: "800",
    textAlign: "center",
    marginBottom: 10,
  },
  separadorTitulo: {
    width: "82%",
    height: 1,
    backgroundColor: "#000000",
    marginBottom: 10,
  },
  tituloCurso: {
    width: "100%",
    flexShrink: 1,
    paddingHorizontal: 10,
    marginBottom: 12,
    color: "#000000",
    fontSize: 16,
    fontWeight: "800",
    lineHeight: 22,
    textAlign: "center",
  },
  previewBox: {
    width: "100%",
    aspectRatio: 297 / 210,
    backgroundColor: "#d1d5db",
    overflow: "hidden",
    borderRadius: 6,
  },
  pdf: { flex: 1, width: "100%" },
  cargando: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(254,162,0,0.85)",
  },
  validacionCard: {
    width: "100%",
    flexShrink: 1,
    marginTop: 10,
    marginBottom: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: "center",
  },
  validacionCardValidada: {
    backgroundColor: "#EAF7F0",
    borderColor: "#16834B",
  },
  validacionCardPendiente: {
    backgroundColor: "#FFF5DD",
    borderColor: "#D28A00",
  },
  validacionEstado: {
    width: "100%",
    flexShrink: 1,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  validacionEstadoValidada: {
    color: "#16834B",
  },
  validacionEstadoPendiente: {
    color: "#8A5A00",
  },
  validacionEtiqueta: {
    marginTop: 6,
    color: "#263238",
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
  },
  validacionNombre: {
    marginTop: 1,
    color: "#263238",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  validacionFecha: {
    marginTop: 6,
    color: "#263238",
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
  },
  validacionMensaje: {
    width: "100%",
    flexShrink: 1,
    marginTop: 6,
    color: "#5B4630",
    fontSize: 12,
    lineHeight: 17,
    textAlign: "center",
  },
  acciones: {
    width: "100%",
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  botonCerrar: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#005CFE",
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
  },
  botonDescargar: {
    flex: 1,
    minHeight: 44,
    borderRadius: 10,
    backgroundColor: "#005CFE",
    alignItems: "center",
    justifyContent: "center",
  },
  textoCerrar: { color: "#005CFE", fontSize: 15, fontWeight: "700" },
  textoDescargar: { color: "#ffffff", fontSize: 15, fontWeight: "700" },
});
